---
- name: configure repos
  include_tasks: "{{ (ansible_distribution) | lower }}.yml"
  when: "ansible_distribution | lower == 'ubuntu'"

- name: install nginx
  package:
    name: nginx
    state: present
  notify: enable nginx
  when: "'nginx' not in ansible_facts.packages"

- name: Disable SELinux
  ansible.posix.selinux:
    state: disabled
  when: "ansible_distribution | lower == 'rocky'"

- name: copy config files if needed
  template:
    src: '{{ item.src }}'
    dest: /etc/nginx/conf.d/{{ item.path }}
    owner: root
    group: root
    mode: 0644
  with_community.general.filetree: files/{{inventory_hostname}}/sites/
  notify: reload nginx
  when: item.state == 'file'

- name: delete nginx default.conf
  file:
    path: /etc/nginx/conf.d/default.conf
    state: absent
  notify: reload nginx
...