---
- name: Common deployment
  hosts: all
  become: yes
  pre_tasks:
    - name: Gather the package facts
      ansible.builtin.package_facts:
        manager: auto
  roles:
    - ping

- name: iscsi server deployment
  hosts: iscsi-server
  become: yes
  roles:
    - iscsi

- name: Pacemaker deployment
  hosts: nodes
  become: yes
  roles:
    - pacemaker

- name: Frontend play
  hosts: frontends
  become: yes
  roles:
    - nginx

- name: Backend play
  hosts: backends
  become: yes
  roles:
    - nginx
    - docker
    - backdrop
...