services:
  backdrop-1:
    image: backdrop
    environment:
      - BACKDROP_DB_HOST=db
      - BACKDROP_DB_PORT=3306
      - BACKDROP_DB_USER=backdrop
      - BACKDROP_DB_PASSWORD=backdrop
    ports:
      - '127.0.0.1:8081:80'
    networks:
      - cms
    depends_on:
      - db

  backdrop-2:
    image: backdrop
    environment:
      - BACKDROP_DB_HOST=db
      - BACKDROP_DB_PORT=3306
      - BACKDROP_DB_USER=backdrop
      - BACKDROP_DB_PASSWORD=backdrop
    ports:
      - '127.0.0.1:8082:80'
    networks:
      - cms
    depends_on:
      - db

  backdrop-3:
    image: backdrop
    environment:
      - BACKDROP_DB_HOST=db
      - BACKDROP_DB_PORT=3306
      - BACKDROP_DB_USER=backdrop
      - BACKDROP_DB_PASSWORD=backdrop
    ports:
      - '127.0.0.1:8083:80'
    networks:
      - cms
    depends_on:
      - db

  db:
    image: mysql
    environment:
      MYSQL_USER: backdrop
      MYSQL_PASSWORD: backdrop
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_DATABASE: backdrop
    networks:
      - cms
networks:
  cms:
    driver: bridge