---
- name: ensure old versions of docker are not installed
  package:
    name: "{{ item }}"
    state: absent
  loop:
    - containerd
    - docker-compose
    - docker-compose-v2
    - docker-doc
    - docker-engine
    - docker.io
    - podman-docker
    - runc
  when: item in ansible_facts.packages

- name: install requirements
  package:
    name: "{{ item }}"
  loop:
    - ca-certificates
    - gnupg
  when: item not in ansible_facts.packages

- name: configure repos
  include_tasks: "{{ (ansible_distribution) | lower }}.yml"

- name: install docker components
  package:
    name: "{{ item }}"
    state: present
  loop:
    - docker-ce
    - docker-ce-cli
    - containerd.io
    - docker-buildx-plugin
    - docker-compose-plugin
  when: item not in ansible_facts.packages
  notify: start docker

- meta: flush_handlers
...