- block:
    - name: Add Docker key
      get_url:
        url: 'https://download.docker.com/linux/ubuntu/gpg'
        dest: '/etc/apt/trusted.gpg.d/docker.asc'
        mode: 0644

    - name: 'Add Docker repo'
      apt_repository:
        repo: >
          deb [arch=amd64 signed-by=/etc/apt/trusted.gpg.d/docker.asc]
          https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
        filename: 'docker.list'

    - name: update cache
      apt:
        update_cache: true
        cache_valid_time: 3600  #1 hour
  when: '"docker-ce" not in ansible_facts.packages'